In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("deliveryTimeData2.csv")

In [3]:
df.head()

   Delivery Time Y(min)  Number Of Cases x1  Distance,x2(ft)
0                 16.68                   7              560
1                 11.50                   3              220
2                 12.03                   3              340
3                 14.88                   4               80
4                 13.75                   6              150

In [7]:
df.tail()

    Delivery Time Y(min)  Number Of Cases x1  Distance,x2(ft)
20                 17.90                  10              140
21                 52.32                  26              810
22                 18.75                   9              450
23                 19.83                   8              635
24                 10.75                   4              150

In [ ]:

def