# Markov Chain Analysis on Soft Drink Preference
### Md Neaz Ali
### Department: Statistics
### session:        2017-18
#### Roll:                  1722019

In [1]:
import random
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('soft_drink.csv')
df.head()

           Name                       Email  Status  Current State Next State
0  Naimur Munna      naimurmunna1@gmail.com  Student     Coca Cola         RC
1   Md Neaz Ali         neazali77@gmail.com  Student        Sprite  Coca Cola
2      HR ANTOR           antorhr@gmail.com  Student     Coca Cola  Coca Cola
3         Nayem           nkiu016@gmail.com  Student        Sprite      Pepsi
4       Shakib   shakibrahman1122@gmail.com  Student     Coca Cola     Sprite

## Current State and Next State

In [29]:
cstate = df['Current State']
nstate = df['Next State']

In [4]:
tpm = pd.crosstab(cstate,nstate)
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1

In [5]:
tpm = np.array(tpm)
tpm

array([[14, 12,  3, 16],
       [ 1,  0,  0,  0],
       [ 1,  0,  1,  0],
       [ 7,  2,  2,  1]])

In [6]:
rowSums = np.sum(tpm,1)
rowSums

array([45,  1,  2, 12])

In [7]:
TPM = tpm.transpose()/rowSums
TPM = TPM.transpose()

# Case 1: P(x10=2)

In [30]:
type(cstate)

pandas.core.series.Series

In [31]:
cstate.value_counts()

Coca Cola    45
Sprite       12
RC            2
Pepsi         1
Name: Current State, dtype: int64

In [ ]:
cstate = np.array(cstate.value_counts())

In [35]:
cstate = np.array(cstate)

In [38]:
cstate = cstate/sum(cstate)
cstate

array([0.75      , 0.2       , 0.03333333, 0.01666667])

In [29]:
temp = TPM
temp

array([[0.31111111, 0.26666667, 0.06666667, 0.35555556],
       [1.        , 0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.58333333, 0.16666667, 0.16666667, 0.08333333]])

In [34]:
n = 10
for i in range(0,n):
    temp = np.matmul(temp,TPM)
temp

array([[0.50458716, 0.16717635, 0.13251784, 0.19571865],
       [0.50458716, 0.16717635, 0.13251784, 0.19571865],
       [0.50458716, 0.16717635, 0.13251784, 0.19571865],
       [0.50458716, 0.16717635, 0.13251784, 0.19571865]])

In [39]:
qjPn=np.matmul(cstate,temp)

In [40]:
qjPn

array([0.50458716, 0.16717635, 0.13251784, 0.19571865])

In [41]:
qjPn[2]

0.13251783893985733

# Case 2: P(x15=2|x0=0)

In [42]:
steps = 15
curr_state = 0
next_state = 2
temp = TPM
for i in range(0,steps):
    temp = np.matmul(temp,TPM)
temp[curr_state,next_state]

0.13251773369523148

# Random Walk on Markov Chain
### for 15 Steps

In [13]:
states = ["Coca Cola","Pepsi","RC","Sprite"]
n = 15
start_state = 0 # starting with coacola
print(states[start_state],"-->",end=" ")
prev_state = start_state
for i in range(0,n):
    curr_state = np.random.choice([0,1,2,3],p=TPM[prev_state])
    print(states[curr_state],"-->",end=" ")
    prev_state = curr_state
print("Stop")

Coca Cola --> Sprite --> Coca Cola --> Pepsi --> Coca Cola --> Pepsi --> Coca Cola --> Sprite --> Coca Cola --> Pepsi --> Coca Cola --> Sprite --> RC --> RC --> RC --> RC --> Stop

### We can perform the random walk for different states

# Stationary For Transition Probability Matrix

In [14]:
steps = 10**6
start_state = 0
pi = np.array([0,0,0,0])
pi[start_state]=1
prev_state = start_state
i = 0
while i<steps:
    curr_state = np.random.choice([0,1,2,3],p=TPM[prev_state])
    pi[curr_state]+=1
    i+=1
pi = pi/steps
pi

array([0.311278, 0.266158, 0.066601, 0.355964])

In [ ]:
steps9 = 9
start_state=0
pi = np.array([0,0,0,0])
pi[start_state]=1
prev_state = start_state
i = 0
while i<steps:
    curr_state = np.random.choice([0,1,2,3],p=TPM[prev_state])
    pi[curr_state]+=1
    i+=1
pi = pi/steps